name: thing_toast
description: "Package for Fancy Gradient Toast."
version: 1.0.0
repository: https://github.com/codestrdy/thing_toast

environment:
  sdk: ^3.10.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
